cfg: ./models/yolov5s.yaml
data: ./data/coco128.yaml
hyp: ''
epochs: 1
batch_size: 2
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
weights: yolov5s.pt
name: ''
device: ''
multi_scale: false
single_cls: false
sync_bn: false
local_rank: -1
total_batch_size: 2
world_size: 1
